# Generated by Django 3.0.2 on 2020-04-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20200412_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=50)),
                ('appointment_date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
