# Generated by Django 3.0.2 on 2020-04-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='appointment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
