# Generated by Django 3.0.2 on 2020-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_consultation_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='appointment_id',
            field=models.IntegerField(null=True),
        ),
    ]
