# Generated by Django 3.0.2 on 2020-04-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20200414_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='username',
        ),
    ]
