# Generated by Django 3.0.2 on 2020-04-14 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_remove_consultation_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='username',
            field=models.CharField(default=datetime.datetime(2020, 4, 14, 13, 55, 9, 265865, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
