# Generated by Django 3.0.2 on 2020-04-15 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_consultation_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vote',
            field=models.CharField(blank=True, choices=[('u', 'upvote'), ('d', 'downvote')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='vote',
            field=models.CharField(choices=[('u', 'upvote'), ('d', 'downvote')], default='upvote', max_length=1),
        ),
    ]
