# Generated by Django 3.0.5 on 2020-04-21 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_auto_20200415_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='type1',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='contact_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='specialist',
            field=models.CharField(blank=True, choices=[('general', 'general'), ('neurologist', 'neurologist'), ('cardiologist', 'cardiologist'), ('dermatologist', 'dermatologist'), ('pediatrician', 'pediatrician'), ('psychiatrist', 'psychiatrist'), ('orthopedician', 'orthopedician')], default='general', max_length=50),
        ),
    ]
